name: Build and Publish Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run electron-build:package:linux

      - name: Publish to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          asset-path: ./dist/*.AppImage
          github-token: ${{ secrets.GITHUB_TOKEN }}
